name = "Server Modpack"
author = "NastyGamer"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c71d040448ab0cda57089e909ea663cec64880749bbaaed645b2f1b28af8b32b"

[versions]
forge = "38.0.17"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
