name = "Server Modpack"
author = "NastyGamer"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e0c402f15aca7d48cbf7fdaf31cbd8c6c795508ac162583e15413d0018ac58f"

[versions]
forge = "38.0.17"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
