name = "Server Modpack"
author = "NastyGamer"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59f5ff05f84a5edc8c7d9e68355675a62b87ac14e969daa8d2b95555770ad5b7"

[versions]
forge = "38.0.17"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
