name = "Server Modpack"
author = "NastyGamer"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9bb77c6e5133594b382f14f437dff293fd0bcc098f79a8c8b171b5351cbacc"

[versions]
forge = "38.0.17"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
