name = "Server Modpack"
author = "NastyGamer"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bea3c75a617e9d2218a0d38244ff75bb9d2a513210756e081c7393328bdeb18"

[versions]
forge = "38.0.17"
minecraft = "1.18"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
