name = "Apotheosis"
filename = "Apotheosis-1.18.1-5.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3647/864/Apotheosis-1.18.1-5.3.3.jar"
hash-format = "murmur2"
hash = "6923277"

[update]
[update.curseforge]
file-id = 3647864
project-id = 313970
