name = "Ballistix"
filename = "Ballistix-1.18.1-0.5.0-0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/655/Ballistix-1.18.1-0.5.0-0.jar"
hash-format = "murmur2"
hash = "2385504550"

[update]
[update.curseforge]
file-id = 3620655
project-id = 443915
