name = "BdLib"
filename = "bdlib-1.18.0.5-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/404/bdlib-1.18.0.5-mc1.18.1.jar"
hash-format = "murmur2"
hash = "222392017"

[update]
[update.curseforge]
file-id = 3641404
project-id = 70496
