name = "BdLib"
filename = "bdlib-1.18.1.8-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/245/bdlib-1.18.1.8-mc1.18.1.jar"
hash-format = "murmur2"
hash = "2709068202"

[update]
[update.curseforge]
file-id = 3648245
project-id = 70496
