name = "Blastcraft mod"
filename = "Blastcraft-1.18.1-0.2.5-0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/567/Blastcraft-1.18.1-0.2.5-0.jar"
hash-format = "murmur2"
hash = "3120439255"

[update]
[update.curseforge]
file-id = 3620567
project-id = 405322
