name = "Common Capabilities"
filename = "CommonCapabilities-1.18.1-2.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/170/CommonCapabilities-1.18.1-2.8.2.jar"
hash-format = "murmur2"
hash = "751241209"

[update]
[update.curseforge]
file-id = 3640170
project-id = 247007
