name = "Integrated Terminals"
filename = "IntegratedTerminals-1.18.1-1.2.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/304/IntegratedTerminals-1.18.1-1.2.14.jar"
hash-format = "murmur2"
hash = "1393048448"

[update]
[update.curseforge]
file-id = 3640304
project-id = 295910
