name = "Integrated Dynamics"
filename = "IntegratedDynamics-1.18.1-1.10.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/182/IntegratedDynamics-1.18.1-1.10.9.jar"
hash-format = "murmur2"
hash = "3729247347"

[update]
[update.curseforge]
file-id = 3640182
project-id = 236307
