name = "Just Enough Items (JEI)"
filename = "jei-1.18.1-9.3.2.92.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/318/jei-1.18.1-9.3.2.92.jar"
hash-format = "murmur2"
hash = "436322489"

[update]
[update.curseforge]
file-id = 3645318
project-id = 238222
