name = "Just Enough Items (JEI)"
filename = "jei-1.18.1-9.2.3.85.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/665/jei-1.18.1-9.2.3.85.jar"
hash-format = "murmur2"
hash = "3250177017"

[update]
[update.curseforge]
file-id = 3641665
project-id = 238222
