name = "MrCrayfish's Gun Mod"
filename = "gun-mod-1.1.3-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/948/gun-mod-1.1.3-1.18.1.jar"
hash-format = "murmur2"
hash = "2055916915"

[update]
[update.curseforge]
file-id = 3622948
project-id = 289479
