name = "SimpleOres"
filename = "SimpleOres2-1.18.1-4.0.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/790/SimpleOres2-1.18.1-4.0.0.0.jar"
hash-format = "murmur2"
hash = "2958753563"

[update]
[update.curseforge]
file-id = 3620790
project-id = 226138
