name = "SimpleCore API"
filename = "SimpleCoreLib-1.18.1-4.0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/779/SimpleCoreLib-1.18.1-4.0.0.2.jar"
hash-format = "murmur2"
hash = "3117707744"

[update]
[update.curseforge]
file-id = 3620779
project-id = 226136
