name = "SimpleCore API"
filename = "SimpleCoreLib-1.18.1-4.0.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/317/SimpleCoreLib-1.18.1-4.0.0.4.jar"
hash-format = "murmur2"
hash = "2776859219"

[update]
[update.curseforge]
file-id = 3646317
project-id = 226136
