name = "The One Probe"
filename = "theoneprobe-1.18-5.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/616/theoneprobe-1.18-5.0.3.jar"
hash-format = "murmur2"
hash = "2315277528"

[update]
[update.curseforge]
file-id = 3606616
project-id = 245211
