name = "True Darkness"
filename = "darkness-forge-mc118-2.0.89.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/758/darkness-forge-mc118-2.0.89.jar"
hash-format = "murmur2"
hash = "3695795510"

[update]
[update.curseforge]
file-id = 3566758
project-id = 337243
